### ISSUE TITLE
Property or indexer 'IOpenApiMediaType.Example' cannot be assigned to -- it is read only

### ISSUE THREAD

**Issue by rdeveen** [microsoft/OpenAPI.NET#2582]
**Describe the bug**
Just a simple .NET API with OpenAPI support and generation of Open API Specification. Was working on the 2.3.9 version but now refused to build on the 3.0.0 version.

`C:\Sources\api\src\Api\obj\Debug\net10.0\Microsoft.AspNetCore.OpenApi.SourceGenerators\Microsoft.AspNetCore.OpenApi.SourceGenerators.XmlCommentGenerator\OpenApiXmlCommentSupport.generated.cs(460,41,460,58): error CS0200: Property or indexer 'IOpenApiMediaType.Example' cannot be assigned to -- it is read only`

**OpenApi File To Reproduce**
Add the OpenApi file you're using or a link to it as well as the steps to reproduce the current behavior.

**Expected behavior**

**Screenshots/Code Snippets**
If applicable, add screenshots of the stack trace or a code snippet to help explain your problem.
If applicable, add a link to your project

**Additional context**

**Comment by rdeveen** [comment]
Sorry, not your fault, see: https://github.com/dotnet/aspnetcore/issues/64317
